### ISSUE TITLE
I should be able to designate the translation to choices inputs from the ymal

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/shi18ny#13]
Example

```
agg:
  show: true
  input_type: selectizeInput
  input_params:
    label: Aggregation
    choices:
      i_total:
      - sum
      i_mean:
      - mean
      i_median:
      - median
    selected: discrete
```
the choices name with "i_" is the word assign for know if translate or no
